---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sujchinn-podinfo
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:default-*
spec:
  releaseName: podinfo-default
  chart:
    git: git@github.com:sujeeth-alef/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: suji961991/podinfo:default-8.0.0
    replicaCount: 1
